from __future__ import annotations

from pydantic import BaseModel, Field


class FeedbackRequest(BaseModel):
    codigo_estudiante: str = Field(max_length=10000)
    error_output: str = Field(max_length=5000)
    session_id: str  # required — generated by browser, never falls back to IP


class FeedbackResponse(BaseModel):
    retroalimentacion: str
    pregunta_guia: str | None = None
    referencia_concepto: str | None = None
    mostrar_pista: bool = True
    silencio: bool = False
    limite: bool = False
